/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// MatchResultResponse
    /// </summary>
    [DataContract(Name = "MatchResultResponse")]
    public partial class MatchResultResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchResultResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchResultResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchResultResponse" /> class.
        /// </summary>
        /// <param name="matchInfo">Match metadata (required).</param>
        /// <param name="players">List of skill rating updates per player. One per player. (required).</param>
        /// <param name="teams">List of team update result (required).</param>
        public MatchResultResponse(MatchInfo matchInfo = default(MatchInfo), Collection<PlayerResult> players = default(Collection<PlayerResult>), Collection<TeamResult> teams = default(Collection<TeamResult>))
        {
            // to ensure "matchInfo" is required (not null)
            if (matchInfo == null)
            {
                throw new ArgumentNullException("matchInfo is a required property for MatchResultResponse and cannot be null");
            }
            this._MatchInfo = matchInfo;
            // to ensure "players" is required (not null)
            if (players == null)
            {
                throw new ArgumentNullException("players is a required property for MatchResultResponse and cannot be null");
            }
            this._Players = players;
            // to ensure "teams" is required (not null)
            if (teams == null)
            {
                throw new ArgumentNullException("teams is a required property for MatchResultResponse and cannot be null");
            }
            this._Teams = teams;
        }

        /// <summary>
        /// Match metadata
        /// </summary>
        /// <value>Match metadata</value>
        [DataMember(Name = "match_info", IsRequired = true, EmitDefaultValue = true)]
        public MatchInfo MatchInfo
        {
            get{ return _MatchInfo;}
            set
            {
                _MatchInfo = value;
                _flagMatchInfo = true;
            }
        }
        private MatchInfo _MatchInfo;
        private bool _flagMatchInfo;

        /// <summary>
        /// Returns false as MatchInfo should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMatchInfo()
        {
            return _flagMatchInfo;
        }
        /// <summary>
        /// List of skill rating updates per player. One per player.
        /// </summary>
        /// <value>List of skill rating updates per player. One per player.</value>
        [DataMember(Name = "players", IsRequired = true, EmitDefaultValue = true)]
        public Collection<PlayerResult> Players
        {
            get{ return _Players;}
            set
            {
                _Players = value;
                _flagPlayers = true;
            }
        }
        private Collection<PlayerResult> _Players;
        private bool _flagPlayers;

        /// <summary>
        /// Returns false as Players should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePlayers()
        {
            return _flagPlayers;
        }
        /// <summary>
        /// List of team update result
        /// </summary>
        /// <value>List of team update result</value>
        [DataMember(Name = "teams", IsRequired = true, EmitDefaultValue = true)]
        public Collection<TeamResult> Teams
        {
            get{ return _Teams;}
            set
            {
                _Teams = value;
                _flagTeams = true;
            }
        }
        private Collection<TeamResult> _Teams;
        private bool _flagTeams;

        /// <summary>
        /// Returns false as Teams should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTeams()
        {
            return _flagTeams;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchResultResponse {\n");
            sb.Append("  MatchInfo: ").Append(MatchInfo).Append("\n");
            sb.Append("  Players: ").Append(Players).Append("\n");
            sb.Append("  Teams: ").Append(Teams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
