/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// MatchMetadata
    /// </summary>
    [DataContract(Name = "MatchMetadata")]
    public partial class MatchMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchMetadata" /> class.
        /// </summary>
        /// <param name="gameMode">The gamemode for this match..</param>
        /// <param name="season">The season the match was played in.</param>
        public MatchMetadata(string gameMode = default(string), int? season = default(int?))
        {
            this.GameMode = gameMode;
            this.Season = season;
        }

        /// <summary>
        /// The gamemode for this match.
        /// </summary>
        /// <value>The gamemode for this match.</value>
        [DataMember(Name = "game_mode", EmitDefaultValue = true)]
        public string GameMode { get; set; }

        /// <summary>
        /// The season the match was played in
        /// </summary>
        /// <value>The season the match was played in</value>
        [DataMember(Name = "season", EmitDefaultValue = true)]
        public int? Season { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchMetadata {\n");
            sb.Append("  GameMode: ").Append(GameMode).Append("\n");
            sb.Append("  Season: ").Append(Season).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Season (int?) minimum
            if (this.Season < (int?)0)
            {
                yield return new ValidationResult("Invalid value for Season, must be a value greater than or equal to 0.", new [] { "Season" });
            }

            yield break;
        }
    }

}
