/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PlayerUpdateExtended
    /// </summary>
    [DataContract(Name = "PlayerUpdateExtended")]
    public partial class PlayerUpdateExtended : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerUpdateExtended" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerUpdateExtended() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerUpdateExtended" /> class.
        /// </summary>
        /// <param name="alpha">Calculated scale factor for uncertainty and step sizes typically &#x3D; 1.0 outside of placement (required).</param>
        /// <param name="botLevel">botLevel (required).</param>
        /// <param name="isBot">Passthrough from request (required).</param>
        /// <param name="isFinalPlacement">Was this the last match of placement (required).</param>
        /// <param name="maxTs">maxTs (required).</param>
        /// <param name="minTs">minTs (required).</param>
        /// <param name="mmrDelta">Change in MMR after this match (required).</param>
        /// <param name="placementFrac">All the teams the player was a part of during this match Fraction of placement completed (max of 1.0, but can be negative) (required).</param>
        /// <param name="playerExpected">Expected individual outcome for the player (0-1) potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs (required).</param>
        /// <param name="playerOutcome">Actual individual outcome for the player (0-1) (required).</param>
        /// <param name="playerScoreRate">Player score per time unit (required).</param>
        /// <param name="playerWeight">How much weight individual outcome has to influence MMR (required).</param>
        /// <param name="residual">Difference between actual and expected outcomes (prediction error) (required).</param>
        /// <param name="sessionCount">Total number of sessions for this player during this match (required).</param>
        /// <param name="teamCount">The amount of teams the player was a part of during this match (required).</param>
        /// <param name="teamExpected">Weighted average of expected outcomes of all teams this player was a member of (required).</param>
        /// <param name="teamOutcome">Weighted average of actual outcomes of all teams this player was a memeber of (required).</param>
        /// <param name="teamWeight">How much weight team outcome has to influences MMR (required).</param>
        /// <param name="unifiedExpected">Combined team and individual expected outcomes (required).</param>
        /// <param name="unifiedExpectedDist">The Beta distribution of expected outcomes Encodes how much certainty we have about the unified expected outcome (required).</param>
        /// <param name="unifiedOutcome">Combined team and individual actual outcomes (required).</param>
        public PlayerUpdateExtended(double alpha = default(double), double botLevel = default(double), bool isBot = default(bool), bool isFinalPlacement = default(bool), double maxTs = default(double), double minTs = default(double), double mmrDelta = default(double), double placementFrac = default(double), double playerExpected = default(double), double playerOutcome = default(double), double playerScoreRate = default(double), double playerWeight = default(double), double residual = default(double), int sessionCount = default(int), int teamCount = default(int), double teamExpected = default(double), double teamOutcome = default(double), double teamWeight = default(double), double unifiedExpected = default(double), BetaDistribution unifiedExpectedDist = default(BetaDistribution), double unifiedOutcome = default(double))
        {
            this.Alpha = alpha;
            this.BotLevel = botLevel;
            this.IsBot = isBot;
            this.IsFinalPlacement = isFinalPlacement;
            this.MaxTs = maxTs;
            this.MinTs = minTs;
            this.MmrDelta = mmrDelta;
            this.PlacementFrac = placementFrac;
            this.PlayerExpected = playerExpected;
            this.PlayerOutcome = playerOutcome;
            this.PlayerScoreRate = playerScoreRate;
            this.PlayerWeight = playerWeight;
            this.Residual = residual;
            this.SessionCount = sessionCount;
            this.TeamCount = teamCount;
            this.TeamExpected = teamExpected;
            this.TeamOutcome = teamOutcome;
            this.TeamWeight = teamWeight;
            this.UnifiedExpected = unifiedExpected;
            // to ensure "unifiedExpectedDist" is required (not null)
            if (unifiedExpectedDist == null)
            {
                throw new ArgumentNullException("unifiedExpectedDist is a required property for PlayerUpdateExtended and cannot be null");
            }
            this.UnifiedExpectedDist = unifiedExpectedDist;
            this.UnifiedOutcome = unifiedOutcome;
        }

        /// <summary>
        /// Calculated scale factor for uncertainty and step sizes typically &#x3D; 1.0 outside of placement
        /// </summary>
        /// <value>Calculated scale factor for uncertainty and step sizes typically &#x3D; 1.0 outside of placement</value>
        [DataMember(Name = "alpha", IsRequired = true, EmitDefaultValue = false)]
        public double Alpha { get; set; }

        /// <summary>
        /// Gets or Sets BotLevel
        /// </summary>
        [DataMember(Name = "bot_level", IsRequired = true, EmitDefaultValue = false)]
        public double BotLevel { get; set; }

        /// <summary>
        /// Passthrough from request
        /// </summary>
        /// <value>Passthrough from request</value>
        [DataMember(Name = "is_bot", IsRequired = true, EmitDefaultValue = false)]
        public bool IsBot { get; set; }

        /// <summary>
        /// Was this the last match of placement
        /// </summary>
        /// <value>Was this the last match of placement</value>
        [DataMember(Name = "is_final_placement", IsRequired = true, EmitDefaultValue = false)]
        public bool IsFinalPlacement { get; set; }

        /// <summary>
        /// Gets or Sets MaxTs
        /// </summary>
        [DataMember(Name = "max_ts", IsRequired = true, EmitDefaultValue = false)]
        public double MaxTs { get; set; }

        /// <summary>
        /// Gets or Sets MinTs
        /// </summary>
        [DataMember(Name = "min_ts", IsRequired = true, EmitDefaultValue = false)]
        public double MinTs { get; set; }

        /// <summary>
        /// Change in MMR after this match
        /// </summary>
        /// <value>Change in MMR after this match</value>
        [DataMember(Name = "mmr_delta", IsRequired = true, EmitDefaultValue = false)]
        public double MmrDelta { get; set; }

        /// <summary>
        /// All the teams the player was a part of during this match Fraction of placement completed (max of 1.0, but can be negative)
        /// </summary>
        /// <value>All the teams the player was a part of during this match Fraction of placement completed (max of 1.0, but can be negative)</value>
        [DataMember(Name = "placement_frac", IsRequired = true, EmitDefaultValue = false)]
        public double PlacementFrac { get; set; }

        /// <summary>
        /// Expected individual outcome for the player (0-1) potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs
        /// </summary>
        /// <value>Expected individual outcome for the player (0-1) potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs</value>
        [DataMember(Name = "player_expected", IsRequired = true, EmitDefaultValue = false)]
        public double PlayerExpected { get; set; }

        /// <summary>
        /// Actual individual outcome for the player (0-1)
        /// </summary>
        /// <value>Actual individual outcome for the player (0-1)</value>
        [DataMember(Name = "player_outcome", IsRequired = true, EmitDefaultValue = false)]
        public double PlayerOutcome { get; set; }

        /// <summary>
        /// Player score per time unit
        /// </summary>
        /// <value>Player score per time unit</value>
        [DataMember(Name = "player_score_rate", IsRequired = true, EmitDefaultValue = false)]
        public double PlayerScoreRate { get; set; }

        /// <summary>
        /// How much weight individual outcome has to influence MMR
        /// </summary>
        /// <value>How much weight individual outcome has to influence MMR</value>
        [DataMember(Name = "player_weight", IsRequired = true, EmitDefaultValue = false)]
        public double PlayerWeight { get; set; }

        /// <summary>
        /// Difference between actual and expected outcomes (prediction error)
        /// </summary>
        /// <value>Difference between actual and expected outcomes (prediction error)</value>
        [DataMember(Name = "residual", IsRequired = true, EmitDefaultValue = false)]
        public double Residual { get; set; }

        /// <summary>
        /// Total number of sessions for this player during this match
        /// </summary>
        /// <value>Total number of sessions for this player during this match</value>
        [DataMember(Name = "session_count", IsRequired = true, EmitDefaultValue = false)]
        public int SessionCount { get; set; }

        /// <summary>
        /// The amount of teams the player was a part of during this match
        /// </summary>
        /// <value>The amount of teams the player was a part of during this match</value>
        [DataMember(Name = "team_count", IsRequired = true, EmitDefaultValue = false)]
        public int TeamCount { get; set; }

        /// <summary>
        /// Weighted average of expected outcomes of all teams this player was a member of
        /// </summary>
        /// <value>Weighted average of expected outcomes of all teams this player was a member of</value>
        [DataMember(Name = "team_expected", IsRequired = true, EmitDefaultValue = false)]
        public double TeamExpected { get; set; }

        /// <summary>
        /// Weighted average of actual outcomes of all teams this player was a memeber of
        /// </summary>
        /// <value>Weighted average of actual outcomes of all teams this player was a memeber of</value>
        [DataMember(Name = "team_outcome", IsRequired = true, EmitDefaultValue = false)]
        public double TeamOutcome { get; set; }

        /// <summary>
        /// How much weight team outcome has to influences MMR
        /// </summary>
        /// <value>How much weight team outcome has to influences MMR</value>
        [DataMember(Name = "team_weight", IsRequired = true, EmitDefaultValue = false)]
        public double TeamWeight { get; set; }

        /// <summary>
        /// Combined team and individual expected outcomes
        /// </summary>
        /// <value>Combined team and individual expected outcomes</value>
        [DataMember(Name = "unified_expected", IsRequired = true, EmitDefaultValue = false)]
        public double UnifiedExpected { get; set; }

        /// <summary>
        /// The Beta distribution of expected outcomes Encodes how much certainty we have about the unified expected outcome
        /// </summary>
        /// <value>The Beta distribution of expected outcomes Encodes how much certainty we have about the unified expected outcome</value>
        [DataMember(Name = "unified_expected_dist", IsRequired = true, EmitDefaultValue = false)]
        public BetaDistribution UnifiedExpectedDist { get; set; }

        /// <summary>
        /// Combined team and individual actual outcomes
        /// </summary>
        /// <value>Combined team and individual actual outcomes</value>
        [DataMember(Name = "unified_outcome", IsRequired = true, EmitDefaultValue = false)]
        public double UnifiedOutcome { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerUpdateExtended {\n");
            sb.Append("  Alpha: ").Append(Alpha).Append("\n");
            sb.Append("  BotLevel: ").Append(BotLevel).Append("\n");
            sb.Append("  IsBot: ").Append(IsBot).Append("\n");
            sb.Append("  IsFinalPlacement: ").Append(IsFinalPlacement).Append("\n");
            sb.Append("  MaxTs: ").Append(MaxTs).Append("\n");
            sb.Append("  MinTs: ").Append(MinTs).Append("\n");
            sb.Append("  MmrDelta: ").Append(MmrDelta).Append("\n");
            sb.Append("  PlacementFrac: ").Append(PlacementFrac).Append("\n");
            sb.Append("  PlayerExpected: ").Append(PlayerExpected).Append("\n");
            sb.Append("  PlayerOutcome: ").Append(PlayerOutcome).Append("\n");
            sb.Append("  PlayerScoreRate: ").Append(PlayerScoreRate).Append("\n");
            sb.Append("  PlayerWeight: ").Append(PlayerWeight).Append("\n");
            sb.Append("  Residual: ").Append(Residual).Append("\n");
            sb.Append("  SessionCount: ").Append(SessionCount).Append("\n");
            sb.Append("  TeamCount: ").Append(TeamCount).Append("\n");
            sb.Append("  TeamExpected: ").Append(TeamExpected).Append("\n");
            sb.Append("  TeamOutcome: ").Append(TeamOutcome).Append("\n");
            sb.Append("  TeamWeight: ").Append(TeamWeight).Append("\n");
            sb.Append("  UnifiedExpected: ").Append(UnifiedExpected).Append("\n");
            sb.Append("  UnifiedExpectedDist: ").Append(UnifiedExpectedDist).Append("\n");
            sb.Append("  UnifiedOutcome: ").Append(UnifiedOutcome).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SessionCount (int) minimum
            if (this.SessionCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for SessionCount, must be a value greater than or equal to 0.", new [] { "SessionCount" });
            }

            // TeamCount (int) minimum
            if (this.TeamCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for TeamCount, must be a value greater than or equal to 0.", new [] { "TeamCount" });
            }

            yield break;
        }
    }

}
