/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// Start &amp; end timestamp
    /// </summary>
    [DataContract(Name = "PlayerSessionTimestamps")]
    public partial class PlayerSessionTimestamps : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerSessionTimestamps" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerSessionTimestamps() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerSessionTimestamps" /> class.
        /// </summary>
        /// <param name="end">A timestamp of when this playersession ended. (required).</param>
        /// <param name="start">A timestamp of when this playersession started. (required).</param>
        public PlayerSessionTimestamps(double end = default(double), double start = default(double))
        {
            this._End = end;
            this._Start = start;
        }

        /// <summary>
        /// A timestamp of when this playersession ended.
        /// </summary>
        /// <value>A timestamp of when this playersession ended.</value>
        [DataMember(Name = "end", IsRequired = true, EmitDefaultValue = true)]
        public double End
        {
            get{ return _End;}
            set
            {
                _End = value;
                _flagEnd = true;
            }
        }
        private double _End;
        private bool _flagEnd;

        /// <summary>
        /// Returns false as End should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEnd()
        {
            return _flagEnd;
        }
        /// <summary>
        /// A timestamp of when this playersession started.
        /// </summary>
        /// <value>A timestamp of when this playersession started.</value>
        [DataMember(Name = "start", IsRequired = true, EmitDefaultValue = true)]
        public double Start
        {
            get{ return _Start;}
            set
            {
                _Start = value;
                _flagStart = true;
            }
        }
        private double _Start;
        private bool _flagStart;

        /// <summary>
        /// Returns false as Start should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStart()
        {
            return _flagStart;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerSessionTimestamps {\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
