/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PreMatchPlayerResult
    /// </summary>
    [DataContract(Name = "PreMatchPlayerResult")]
    public partial class PreMatchPlayerResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchPlayerResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreMatchPlayerResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchPlayerResult" /> class.
        /// </summary>
        /// <param name="extended">Extended player update information (required).</param>
        /// <param name="playerId">The unique identifier of the player (passed through) (required).</param>
        /// <param name="playerIdx">Internal player index (required).</param>
        /// <param name="post">Updated player stats after this match (required).</param>
        /// <param name="prior">Player stats from the start of this match (required).</param>
        public PreMatchPlayerResult(PreMatchPlayerResultExtended extended = default(PreMatchPlayerResultExtended), string playerId = default(string), int playerIdx = default(int), PriorPlayerStats post = default(PriorPlayerStats), PriorPlayerStats prior = default(PriorPlayerStats))
        {
            // to ensure "extended" is required (not null)
            if (extended == null)
            {
                throw new ArgumentNullException("extended is a required property for PreMatchPlayerResult and cannot be null");
            }
            this.Extended = extended;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for PreMatchPlayerResult and cannot be null");
            }
            this.PlayerId = playerId;
            this.PlayerIdx = playerIdx;
            // to ensure "post" is required (not null)
            if (post == null)
            {
                throw new ArgumentNullException("post is a required property for PreMatchPlayerResult and cannot be null");
            }
            this.Post = post;
            // to ensure "prior" is required (not null)
            if (prior == null)
            {
                throw new ArgumentNullException("prior is a required property for PreMatchPlayerResult and cannot be null");
            }
            this.Prior = prior;
        }

        /// <summary>
        /// Extended player update information
        /// </summary>
        /// <value>Extended player update information</value>
        [DataMember(Name = "extended", IsRequired = true, EmitDefaultValue = false)]
        public PreMatchPlayerResultExtended Extended { get; set; }

        /// <summary>
        /// The unique identifier of the player (passed through)
        /// </summary>
        /// <value>The unique identifier of the player (passed through)</value>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = false)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Internal player index
        /// </summary>
        /// <value>Internal player index</value>
        [DataMember(Name = "player_idx", IsRequired = true, EmitDefaultValue = false)]
        public int PlayerIdx { get; set; }

        /// <summary>
        /// Updated player stats after this match
        /// </summary>
        /// <value>Updated player stats after this match</value>
        [DataMember(Name = "post", IsRequired = true, EmitDefaultValue = false)]
        public PriorPlayerStats Post { get; set; }

        /// <summary>
        /// Player stats from the start of this match
        /// </summary>
        /// <value>Player stats from the start of this match</value>
        [DataMember(Name = "prior", IsRequired = true, EmitDefaultValue = false)]
        public PriorPlayerStats Prior { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreMatchPlayerResult {\n");
            sb.Append("  Extended: ").Append(Extended).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  PlayerIdx: ").Append(PlayerIdx).Append("\n");
            sb.Append("  Post: ").Append(Post).Append("\n");
            sb.Append("  Prior: ").Append(Prior).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PlayerIdx (int) minimum
            if (this.PlayerIdx < (int)0)
            {
                yield return new ValidationResult("Invalid value for PlayerIdx, must be a value greater than or equal to 0.", new [] { "PlayerIdx" });
            }

            yield break;
        }
    }

}
