/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PreMatchTeamResult
    /// </summary>
    [DataContract(Name = "PreMatchTeamResult")]
    public partial class PreMatchTeamResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchTeamResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreMatchTeamResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchTeamResult" /> class.
        /// </summary>
        /// <param name="beta">Total uncertainty in team outcome (required).</param>
        /// <param name="density">The weighted team size (required).</param>
        /// <param name="expected">The expected team outcome based on party and team model (0-1) Potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs (required).</param>
        /// <param name="id">The local identifier of the team (passthrough) (required).</param>
        /// <param name="idx">Zero-indexed team index (required).</param>
        /// <param name="mmr">Total MMR of the team as determined by the party and team models (not necessarily the sum of MMRs) (required).</param>
        /// <param name="partyCount">Total parties in the team (required).</param>
        /// <param name="size">Total player count the team has seen throughout the match (required).</param>
        public PreMatchTeamResult(double beta = default(double), double density = default(double), double expected = default(double), string id = default(string), int idx = default(int), double mmr = default(double), int partyCount = default(int), int size = default(int))
        {
            this._Beta = beta;
            this._Density = density;
            this._Expected = expected;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PreMatchTeamResult and cannot be null");
            }
            this._Id = id;
            this._Idx = idx;
            this._Mmr = mmr;
            this._PartyCount = partyCount;
            this._Size = size;
        }

        /// <summary>
        /// Total uncertainty in team outcome
        /// </summary>
        /// <value>Total uncertainty in team outcome</value>
        [DataMember(Name = "beta", IsRequired = true, EmitDefaultValue = true)]
        public double Beta
        {
            get{ return _Beta;}
            set
            {
                _Beta = value;
                _flagBeta = true;
            }
        }
        private double _Beta;
        private bool _flagBeta;

        /// <summary>
        /// Returns false as Beta should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBeta()
        {
            return _flagBeta;
        }
        /// <summary>
        /// The weighted team size
        /// </summary>
        /// <value>The weighted team size</value>
        [DataMember(Name = "density", IsRequired = true, EmitDefaultValue = true)]
        public double Density
        {
            get{ return _Density;}
            set
            {
                _Density = value;
                _flagDensity = true;
            }
        }
        private double _Density;
        private bool _flagDensity;

        /// <summary>
        /// Returns false as Density should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDensity()
        {
            return _flagDensity;
        }
        /// <summary>
        /// The expected team outcome based on party and team model (0-1) Potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs
        /// </summary>
        /// <value>The expected team outcome based on party and team model (0-1) Potentially clamped to a maximum value (typically 0.8) to guarantee minimum payoffs</value>
        [DataMember(Name = "expected", IsRequired = true, EmitDefaultValue = true)]
        public double Expected
        {
            get{ return _Expected;}
            set
            {
                _Expected = value;
                _flagExpected = true;
            }
        }
        private double _Expected;
        private bool _flagExpected;

        /// <summary>
        /// Returns false as Expected should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeExpected()
        {
            return _flagExpected;
        }
        /// <summary>
        /// The local identifier of the team (passthrough)
        /// </summary>
        /// <value>The local identifier of the team (passthrough)</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private string _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Zero-indexed team index
        /// </summary>
        /// <value>Zero-indexed team index</value>
        [DataMember(Name = "idx", IsRequired = true, EmitDefaultValue = true)]
        public int Idx
        {
            get{ return _Idx;}
            set
            {
                _Idx = value;
                _flagIdx = true;
            }
        }
        private int _Idx;
        private bool _flagIdx;

        /// <summary>
        /// Returns false as Idx should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIdx()
        {
            return _flagIdx;
        }
        /// <summary>
        /// Total MMR of the team as determined by the party and team models (not necessarily the sum of MMRs)
        /// </summary>
        /// <value>Total MMR of the team as determined by the party and team models (not necessarily the sum of MMRs)</value>
        [DataMember(Name = "mmr", IsRequired = true, EmitDefaultValue = true)]
        public double Mmr
        {
            get{ return _Mmr;}
            set
            {
                _Mmr = value;
                _flagMmr = true;
            }
        }
        private double _Mmr;
        private bool _flagMmr;

        /// <summary>
        /// Returns false as Mmr should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMmr()
        {
            return _flagMmr;
        }
        /// <summary>
        /// Total parties in the team
        /// </summary>
        /// <value>Total parties in the team</value>
        [DataMember(Name = "party_count", IsRequired = true, EmitDefaultValue = true)]
        public int PartyCount
        {
            get{ return _PartyCount;}
            set
            {
                _PartyCount = value;
                _flagPartyCount = true;
            }
        }
        private int _PartyCount;
        private bool _flagPartyCount;

        /// <summary>
        /// Returns false as PartyCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePartyCount()
        {
            return _flagPartyCount;
        }
        /// <summary>
        /// Total player count the team has seen throughout the match
        /// </summary>
        /// <value>Total player count the team has seen throughout the match</value>
        [DataMember(Name = "size", IsRequired = true, EmitDefaultValue = true)]
        public int Size
        {
            get{ return _Size;}
            set
            {
                _Size = value;
                _flagSize = true;
            }
        }
        private int _Size;
        private bool _flagSize;

        /// <summary>
        /// Returns false as Size should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSize()
        {
            return _flagSize;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreMatchTeamResult {\n");
            sb.Append("  Beta: ").Append(Beta).Append("\n");
            sb.Append("  Density: ").Append(Density).Append("\n");
            sb.Append("  Expected: ").Append(Expected).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Idx: ").Append(Idx).Append("\n");
            sb.Append("  Mmr: ").Append(Mmr).Append("\n");
            sb.Append("  PartyCount: ").Append(PartyCount).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Idx (int) minimum
            if (this.Idx < (int)0)
            {
                yield return new ValidationResult("Invalid value for Idx, must be a value greater than or equal to 0.", new [] { "Idx" });
            }

            // PartyCount (int) minimum
            if (this.PartyCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for PartyCount, must be a value greater than or equal to 0.", new [] { "PartyCount" });
            }

            // Size (int) minimum
            if (this.Size < (int)0)
            {
                yield return new ValidationResult("Invalid value for Size, must be a value greater than or equal to 0.", new [] { "Size" });
            }

            yield break;
        }
    }

}
