/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PreMatchInfo
    /// </summary>
    [DataContract(Name = "PreMatchInfo")]
    public partial class PreMatchInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreMatchInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchInfo" /> class.
        /// </summary>
        /// <param name="matchId">Passthrough match_id if provided.</param>
        /// <param name="meanMmr">The mean MMR of all players in the match (required).</param>
        /// <param name="mmrDeviation">MMR deviation for this match (useful to determine match quality) (required).</param>
        /// <param name="partyCount">Total parties that were part of this match (required).</param>
        /// <param name="playerCount">Total amount of unique players in this match (required).</param>
        /// <param name="teamCount">Total teams that were part of this match (required).</param>
        public PreMatchInfo(string matchId = default(string), double meanMmr = default(double), double mmrDeviation = default(double), int partyCount = default(int), int playerCount = default(int), int teamCount = default(int))
        {
            this._MeanMmr = meanMmr;
            this._MmrDeviation = mmrDeviation;
            this._PartyCount = partyCount;
            this._PlayerCount = playerCount;
            this._TeamCount = teamCount;
            this._MatchId = matchId;
            if (this.MatchId != null)
            {
                this._flagMatchId = true;
            }
        }

        /// <summary>
        /// Passthrough match_id if provided
        /// </summary>
        /// <value>Passthrough match_id if provided</value>
        [DataMember(Name = "match_id", EmitDefaultValue = true)]
        public string MatchId
        {
            get{ return _MatchId;}
            set
            {
                _MatchId = value;
                _flagMatchId = true;
            }
        }
        private string _MatchId;
        private bool _flagMatchId;

        /// <summary>
        /// Returns false as MatchId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMatchId()
        {
            return _flagMatchId;
        }
        /// <summary>
        /// The mean MMR of all players in the match
        /// </summary>
        /// <value>The mean MMR of all players in the match</value>
        [DataMember(Name = "mean_mmr", IsRequired = true, EmitDefaultValue = true)]
        public double MeanMmr
        {
            get{ return _MeanMmr;}
            set
            {
                _MeanMmr = value;
                _flagMeanMmr = true;
            }
        }
        private double _MeanMmr;
        private bool _flagMeanMmr;

        /// <summary>
        /// Returns false as MeanMmr should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMeanMmr()
        {
            return _flagMeanMmr;
        }
        /// <summary>
        /// MMR deviation for this match (useful to determine match quality)
        /// </summary>
        /// <value>MMR deviation for this match (useful to determine match quality)</value>
        [DataMember(Name = "mmr_deviation", IsRequired = true, EmitDefaultValue = true)]
        public double MmrDeviation
        {
            get{ return _MmrDeviation;}
            set
            {
                _MmrDeviation = value;
                _flagMmrDeviation = true;
            }
        }
        private double _MmrDeviation;
        private bool _flagMmrDeviation;

        /// <summary>
        /// Returns false as MmrDeviation should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMmrDeviation()
        {
            return _flagMmrDeviation;
        }
        /// <summary>
        /// Total parties that were part of this match
        /// </summary>
        /// <value>Total parties that were part of this match</value>
        [DataMember(Name = "party_count", IsRequired = true, EmitDefaultValue = true)]
        public int PartyCount
        {
            get{ return _PartyCount;}
            set
            {
                _PartyCount = value;
                _flagPartyCount = true;
            }
        }
        private int _PartyCount;
        private bool _flagPartyCount;

        /// <summary>
        /// Returns false as PartyCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePartyCount()
        {
            return _flagPartyCount;
        }
        /// <summary>
        /// Total amount of unique players in this match
        /// </summary>
        /// <value>Total amount of unique players in this match</value>
        [DataMember(Name = "player_count", IsRequired = true, EmitDefaultValue = true)]
        public int PlayerCount
        {
            get{ return _PlayerCount;}
            set
            {
                _PlayerCount = value;
                _flagPlayerCount = true;
            }
        }
        private int _PlayerCount;
        private bool _flagPlayerCount;

        /// <summary>
        /// Returns false as PlayerCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePlayerCount()
        {
            return _flagPlayerCount;
        }
        /// <summary>
        /// Total teams that were part of this match
        /// </summary>
        /// <value>Total teams that were part of this match</value>
        [DataMember(Name = "team_count", IsRequired = true, EmitDefaultValue = true)]
        public int TeamCount
        {
            get{ return _TeamCount;}
            set
            {
                _TeamCount = value;
                _flagTeamCount = true;
            }
        }
        private int _TeamCount;
        private bool _flagTeamCount;

        /// <summary>
        /// Returns false as TeamCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTeamCount()
        {
            return _flagTeamCount;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreMatchInfo {\n");
            sb.Append("  MatchId: ").Append(MatchId).Append("\n");
            sb.Append("  MeanMmr: ").Append(MeanMmr).Append("\n");
            sb.Append("  MmrDeviation: ").Append(MmrDeviation).Append("\n");
            sb.Append("  PartyCount: ").Append(PartyCount).Append("\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  TeamCount: ").Append(TeamCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PartyCount (int) minimum
            if (this.PartyCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for PartyCount, must be a value greater than or equal to 0.", new [] { "PartyCount" });
            }

            // PlayerCount (int) minimum
            if (this.PlayerCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for PlayerCount, must be a value greater than or equal to 0.", new [] { "PlayerCount" });
            }

            // TeamCount (int) minimum
            if (this.TeamCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for TeamCount, must be a value greater than or equal to 0.", new [] { "TeamCount" });
            }

            yield break;
        }
    }

}
