/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PreMatchRequest
    /// </summary>
    [DataContract(Name = "PreMatchRequest")]
    public partial class PreMatchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreMatchRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreMatchRequest" /> class.
        /// </summary>
        /// <param name="matchId">Unique match identifier.</param>
        /// <param name="metadata">Several properties to provide more context about the match.</param>
        /// <param name="playerSessions">A list of all player sessions for one single match. There can be multiple sessions for a single player. (required).</param>
        /// <param name="teams">A list of teams and their metadata (required).</param>
        public PreMatchRequest(string matchId = default(string), MatchMetadata metadata = default(MatchMetadata), Collection<PreMatchPlayerSession> playerSessions = default(Collection<PreMatchPlayerSession>), Collection<PreMatchTeamInfo> teams = default(Collection<PreMatchTeamInfo>))
        {
            // to ensure "playerSessions" is required (not null)
            if (playerSessions == null)
            {
                throw new ArgumentNullException("playerSessions is a required property for PreMatchRequest and cannot be null");
            }
            this.PlayerSessions = playerSessions;
            // to ensure "teams" is required (not null)
            if (teams == null)
            {
                throw new ArgumentNullException("teams is a required property for PreMatchRequest and cannot be null");
            }
            this.Teams = teams;
            this.MatchId = matchId;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Unique match identifier
        /// </summary>
        /// <value>Unique match identifier</value>
        [DataMember(Name = "match_id", EmitDefaultValue = false)]
        public string MatchId { get; set; }

        /// <summary>
        /// Several properties to provide more context about the match
        /// </summary>
        /// <value>Several properties to provide more context about the match</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public MatchMetadata Metadata { get; set; }

        /// <summary>
        /// A list of all player sessions for one single match. There can be multiple sessions for a single player.
        /// </summary>
        /// <value>A list of all player sessions for one single match. There can be multiple sessions for a single player.</value>
        [DataMember(Name = "player_sessions", IsRequired = true, EmitDefaultValue = false)]
        public Collection<PreMatchPlayerSession> PlayerSessions { get; set; }

        /// <summary>
        /// A list of teams and their metadata
        /// </summary>
        /// <value>A list of teams and their metadata</value>
        [DataMember(Name = "teams", IsRequired = true, EmitDefaultValue = false)]
        public Collection<PreMatchTeamInfo> Teams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreMatchRequest {\n");
            sb.Append("  MatchId: ").Append(MatchId).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PlayerSessions: ").Append(PlayerSessions).Append("\n");
            sb.Append("  Teams: ").Append(Teams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
