/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invokation.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invokation.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Invokation.Skill.Sdk.Model
{
    /// <summary>
    /// PriorPlayerStats
    /// </summary>
    [DataContract(Name = "PriorPlayerStats")]
    public partial class PriorPlayerStats : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriorPlayerStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PriorPlayerStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PriorPlayerStats" /> class.
        /// </summary>
        /// <param name="gamesPlayed">Amount of games played (required).</param>
        /// <param name="mmr">The player MMR (required).</param>
        /// <param name="momentum">Rolling-average win rate (**if used by model**) (required).</param>
        public PriorPlayerStats(long gamesPlayed = default(long), double mmr = default(double), double momentum = default(double))
        {
            this.GamesPlayed = gamesPlayed;
            this.Mmr = mmr;
            this.Momentum = momentum;
        }

        /// <summary>
        /// Amount of games played
        /// </summary>
        /// <value>Amount of games played</value>
        [DataMember(Name = "games_played", IsRequired = true, EmitDefaultValue = true)]
        public long GamesPlayed { get; set; }

        /// <summary>
        /// The player MMR
        /// </summary>
        /// <value>The player MMR</value>
        [DataMember(Name = "mmr", IsRequired = true, EmitDefaultValue = true)]
        public double Mmr { get; set; }

        /// <summary>
        /// Rolling-average win rate (**if used by model**)
        /// </summary>
        /// <value>Rolling-average win rate (**if used by model**)</value>
        [DataMember(Name = "momentum", IsRequired = true, EmitDefaultValue = true)]
        public double Momentum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PriorPlayerStats {\n");
            sb.Append("  GamesPlayed: ").Append(GamesPlayed).Append("\n");
            sb.Append("  Mmr: ").Append(Mmr).Append("\n");
            sb.Append("  Momentum: ").Append(Momentum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GamesPlayed (long) minimum
            if (this.GamesPlayed < (long)0)
            {
                yield return new ValidationResult("Invalid value for GamesPlayed, must be a value greater than or equal to 0.", new [] { "GamesPlayed" });
            }

            yield break;
        }
    }

}
