/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ivk.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Ivk.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Ivk.Skill.Sdk.Model
{
    /// <summary>
    /// BetaDistribution
    /// </summary>
    [DataContract(Name = "BetaDistribution")]
    public partial class BetaDistribution : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BetaDistribution" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BetaDistribution() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BetaDistribution" /> class.
        /// </summary>
        /// <param name="a">Alpha parameter of the Beta distribution (required).</param>
        /// <param name="b">Beta parameter of the Beta distribution (required).</param>
        public BetaDistribution(double a = default(double), double b = default(double))
        {
            this.A = a;
            this.B = b;
        }

        /// <summary>
        /// Alpha parameter of the Beta distribution
        /// </summary>
        /// <value>Alpha parameter of the Beta distribution</value>
        [DataMember(Name = "a", IsRequired = true, EmitDefaultValue = true)]
        public double A { get; set; }

        /// <summary>
        /// Beta parameter of the Beta distribution
        /// </summary>
        /// <value>Beta parameter of the Beta distribution</value>
        [DataMember(Name = "b", IsRequired = true, EmitDefaultValue = true)]
        public double B { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BetaDistribution {\n");
            sb.Append("  A: ").Append(A).Append("\n");
            sb.Append("  B: ").Append(B).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
