/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ivk.Skill.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Ivk.Skill.Sdk.Client.OpenAPIDateConverter;

namespace Ivk.Skill.Sdk.Model
{
    /// <summary>
    /// MatchInfo
    /// </summary>
    [DataContract(Name = "MatchInfo")]
    public partial class MatchInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchInfo" /> class.
        /// </summary>
        /// <param name="duration">Total duration of the match (required).</param>
        /// <param name="matchId">Passthrough match_id if provided.</param>
        /// <param name="maxTs">The maximum timestamp for the match (required).</param>
        /// <param name="meanMmr">The mean MMR of all players in the match (required).</param>
        /// <param name="minTs">The minimum timestamp for the match (required).</param>
        /// <param name="mmrDeviation">MMR deviation for this match (useful to determine match quality) (required).</param>
        /// <param name="partyCount">Total parties that were part of this match (required).</param>
        /// <param name="playerCount">Total amount of unique players in this match (required).</param>
        /// <param name="teamCount">Total teams that were part of this match (required).</param>
        public MatchInfo(double duration = default(double), string matchId = default(string), double maxTs = default(double), double meanMmr = default(double), double minTs = default(double), double mmrDeviation = default(double), int partyCount = default(int), int playerCount = default(int), int teamCount = default(int))
        {
            this.Duration = duration;
            this.MaxTs = maxTs;
            this.MeanMmr = meanMmr;
            this.MinTs = minTs;
            this.MmrDeviation = mmrDeviation;
            this.PartyCount = partyCount;
            this.PlayerCount = playerCount;
            this.TeamCount = teamCount;
            this.MatchId = matchId;
        }

        /// <summary>
        /// Total duration of the match
        /// </summary>
        /// <value>Total duration of the match</value>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public double Duration { get; set; }

        /// <summary>
        /// Passthrough match_id if provided
        /// </summary>
        /// <value>Passthrough match_id if provided</value>
        [DataMember(Name = "match_id", EmitDefaultValue = true)]
        public string MatchId { get; set; }

        /// <summary>
        /// The maximum timestamp for the match
        /// </summary>
        /// <value>The maximum timestamp for the match</value>
        [DataMember(Name = "max_ts", IsRequired = true, EmitDefaultValue = true)]
        public double MaxTs { get; set; }

        /// <summary>
        /// The mean MMR of all players in the match
        /// </summary>
        /// <value>The mean MMR of all players in the match</value>
        [DataMember(Name = "mean_mmr", IsRequired = true, EmitDefaultValue = true)]
        public double MeanMmr { get; set; }

        /// <summary>
        /// The minimum timestamp for the match
        /// </summary>
        /// <value>The minimum timestamp for the match</value>
        [DataMember(Name = "min_ts", IsRequired = true, EmitDefaultValue = true)]
        public double MinTs { get; set; }

        /// <summary>
        /// MMR deviation for this match (useful to determine match quality)
        /// </summary>
        /// <value>MMR deviation for this match (useful to determine match quality)</value>
        [DataMember(Name = "mmr_deviation", IsRequired = true, EmitDefaultValue = true)]
        public double MmrDeviation { get; set; }

        /// <summary>
        /// Total parties that were part of this match
        /// </summary>
        /// <value>Total parties that were part of this match</value>
        [DataMember(Name = "party_count", IsRequired = true, EmitDefaultValue = true)]
        public int PartyCount { get; set; }

        /// <summary>
        /// Total amount of unique players in this match
        /// </summary>
        /// <value>Total amount of unique players in this match</value>
        [DataMember(Name = "player_count", IsRequired = true, EmitDefaultValue = true)]
        public int PlayerCount { get; set; }

        /// <summary>
        /// Total teams that were part of this match
        /// </summary>
        /// <value>Total teams that were part of this match</value>
        [DataMember(Name = "team_count", IsRequired = true, EmitDefaultValue = true)]
        public int TeamCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchInfo {\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  MatchId: ").Append(MatchId).Append("\n");
            sb.Append("  MaxTs: ").Append(MaxTs).Append("\n");
            sb.Append("  MeanMmr: ").Append(MeanMmr).Append("\n");
            sb.Append("  MinTs: ").Append(MinTs).Append("\n");
            sb.Append("  MmrDeviation: ").Append(MmrDeviation).Append("\n");
            sb.Append("  PartyCount: ").Append(PartyCount).Append("\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  TeamCount: ").Append(TeamCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PartyCount (int) minimum
            if (this.PartyCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for PartyCount, must be a value greater than or equal to 0.", new [] { "PartyCount" });
            }

            // PlayerCount (int) minimum
            if (this.PlayerCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for PlayerCount, must be a value greater than or equal to 0.", new [] { "PlayerCount" });
            }

            // TeamCount (int) minimum
            if (this.TeamCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for TeamCount, must be a value greater than or equal to 0.", new [] { "TeamCount" });
            }

            yield break;
        }
    }

}
