/*
 * Invokation API
 *
 * ## Introduction Welcome to the Invokation REST API.  Soon you too will wield the full power of our skill ratings and matchmaking systems.  ## Authentication The Invokation API uses API keys to authenticate requests. You can view and manage your API keys in the Invokation dashboard.  Your API keys carry many privileges, make sure to keep them secure! Do not share your secret API keys in publicly accessible areas such as Github, client-side code and so forth.  All API requests must be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Calls made over plain HTTP will fail. API requests without authentication will also fail.  ## Compression  You can enable compression by including the `Accept-Encoding` header in your request.  We support the following compression algorithms: `zstd`, `br`, `gzip` or `deflate`.   ## Support If you need help, don't hesitate to reach out to us at support@invokation.games or join our [Community Discord](https://discord.gg/JfNGsunrjX). 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@invokation.games
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Ivk.Skill.Sdk.Client;
using Ivk.Skill.Sdk.Model;

namespace Ivk.Skill.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISkillApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        ///  Get the current active model configuration
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <returns>ConfigurationResponse</returns>
        ConfigurationResponse GetConfiguration(string modelId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        ///  Get the current active model configuration
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <returns>ApiResponse of ConfigurationResponse</returns>
        ApiResponse<ConfigurationResponse> GetConfigurationWithHttpInfo(string modelId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <returns>MatchResultResponse</returns>
        MatchResultResponse PostMatchResult(string modelId, string environment, MatchResultRequest matchResultRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <returns>ApiResponse of MatchResultResponse</returns>
        ApiResponse<MatchResultResponse> PostMatchResultWithHttpInfo(string modelId, string environment, MatchResultRequest matchResultRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Useful to calculate the expected outcome.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <returns>PreMatchResponse</returns>
        PreMatchResponse PostPreMatch(string modelId, string environment, PreMatchRequest preMatchRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Useful to calculate the expected outcome.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <returns>ApiResponse of PreMatchResponse</returns>
        ApiResponse<PreMatchResponse> PostPreMatchWithHttpInfo(string modelId, string environment, PreMatchRequest preMatchRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISkillApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        ///  Get the current active model configuration
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationResponse</returns>
        System.Threading.Tasks.Task<ConfigurationResponse> GetConfigurationAsync(string modelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        ///  Get the current active model configuration
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConfigurationResponse>> GetConfigurationWithHttpInfoAsync(string modelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MatchResultResponse</returns>
        System.Threading.Tasks.Task<MatchResultResponse> PostMatchResultAsync(string modelId, string environment, MatchResultRequest matchResultRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MatchResultResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MatchResultResponse>> PostMatchResultWithHttpInfoAsync(string modelId, string environment, MatchResultRequest matchResultRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Useful to calculate the expected outcome.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PreMatchResponse</returns>
        System.Threading.Tasks.Task<PreMatchResponse> PostPreMatchAsync(string modelId, string environment, PreMatchRequest preMatchRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Useful to calculate the expected outcome.
        /// </remarks>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PreMatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PreMatchResponse>> PostPreMatchWithHttpInfoAsync(string modelId, string environment, PreMatchRequest preMatchRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISkillApi : ISkillApiSync, ISkillApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SkillApi : IDisposable, ISkillApi
    {
        private Ivk.Skill.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SkillApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SkillApi(string basePath)
        {
            this.Configuration = Ivk.Skill.Sdk.Client.Configuration.MergeConfigurations(
                Ivk.Skill.Sdk.Client.GlobalConfiguration.Instance,
                new Ivk.Skill.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Ivk.Skill.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Ivk.Skill.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SkillApi(Ivk.Skill.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Ivk.Skill.Sdk.Client.Configuration.MergeConfigurations(
                Ivk.Skill.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Ivk.Skill.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Ivk.Skill.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SkillApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SkillApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Ivk.Skill.Sdk.Client.Configuration.MergeConfigurations(
                Ivk.Skill.Sdk.Client.GlobalConfiguration.Instance,
                new Ivk.Skill.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Ivk.Skill.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Ivk.Skill.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SkillApi(HttpClient client, Ivk.Skill.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Ivk.Skill.Sdk.Client.Configuration.MergeConfigurations(
                Ivk.Skill.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Ivk.Skill.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Ivk.Skill.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SkillApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SkillApi(Ivk.Skill.Sdk.Client.ISynchronousClient client, Ivk.Skill.Sdk.Client.IAsynchronousClient asyncClient, Ivk.Skill.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Ivk.Skill.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Ivk.Skill.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Ivk.Skill.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Ivk.Skill.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Ivk.Skill.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Ivk.Skill.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///   Get the current active model configuration
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <returns>ConfigurationResponse</returns>
        public ConfigurationResponse GetConfiguration(string modelId)
        {
            Ivk.Skill.Sdk.Client.ApiResponse<ConfigurationResponse> localVarResponse = GetConfigurationWithHttpInfo(modelId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///   Get the current active model configuration
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <returns>ApiResponse of ConfigurationResponse</returns>
        public Ivk.Skill.Sdk.Client.ApiResponse<ConfigurationResponse> GetConfigurationWithHttpInfo(string modelId)
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->GetConfiguration");

            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ConfigurationResponse>("/api/v2/{model_id}/configuration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConfiguration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///   Get the current active model configuration
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationResponse</returns>
        public async System.Threading.Tasks.Task<ConfigurationResponse> GetConfigurationAsync(string modelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ivk.Skill.Sdk.Client.ApiResponse<ConfigurationResponse> localVarResponse = await GetConfigurationWithHttpInfoAsync(modelId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///   Get the current active model configuration
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationResponse)</returns>
        public async System.Threading.Tasks.Task<Ivk.Skill.Sdk.Client.ApiResponse<ConfigurationResponse>> GetConfigurationWithHttpInfoAsync(string modelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->GetConfiguration");


            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ConfigurationResponse>("/api/v2/{model_id}/configuration", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConfiguration", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <returns>MatchResultResponse</returns>
        public MatchResultResponse PostMatchResult(string modelId, string environment, MatchResultRequest matchResultRequest)
        {
            Ivk.Skill.Sdk.Client.ApiResponse<MatchResultResponse> localVarResponse = PostMatchResultWithHttpInfo(modelId, environment, matchResultRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <returns>ApiResponse of MatchResultResponse</returns>
        public Ivk.Skill.Sdk.Client.ApiResponse<MatchResultResponse> PostMatchResultWithHttpInfo(string modelId, string environment, MatchResultRequest matchResultRequest)
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->PostMatchResult");

            // verify the required parameter 'environment' is set
            if (environment == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'environment' when calling SkillApi->PostMatchResult");

            // verify the required parameter 'matchResultRequest' is set
            if (matchResultRequest == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'matchResultRequest' when calling SkillApi->PostMatchResult");

            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("environment", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.Data = matchResultRequest;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<MatchResultResponse>("/api/v2/{model_id}/match_result/{environment}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostMatchResult", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MatchResultResponse</returns>
        public async System.Threading.Tasks.Task<MatchResultResponse> PostMatchResultAsync(string modelId, string environment, MatchResultRequest matchResultRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ivk.Skill.Sdk.Client.ApiResponse<MatchResultResponse> localVarResponse = await PostMatchResultWithHttpInfoAsync(modelId, environment, matchResultRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  During or after the match, you can retrieve skill rating updates based on the provided player sessions.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="matchResultRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MatchResultResponse)</returns>
        public async System.Threading.Tasks.Task<Ivk.Skill.Sdk.Client.ApiResponse<MatchResultResponse>> PostMatchResultWithHttpInfoAsync(string modelId, string environment, MatchResultRequest matchResultRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->PostMatchResult");

            // verify the required parameter 'environment' is set
            if (environment == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'environment' when calling SkillApi->PostMatchResult");

            // verify the required parameter 'matchResultRequest' is set
            if (matchResultRequest == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'matchResultRequest' when calling SkillApi->PostMatchResult");


            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("environment", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.Data = matchResultRequest;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MatchResultResponse>("/api/v2/{model_id}/match_result/{environment}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostMatchResult", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Useful to calculate the expected outcome.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <returns>PreMatchResponse</returns>
        public PreMatchResponse PostPreMatch(string modelId, string environment, PreMatchRequest preMatchRequest)
        {
            Ivk.Skill.Sdk.Client.ApiResponse<PreMatchResponse> localVarResponse = PostPreMatchWithHttpInfo(modelId, environment, preMatchRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Useful to calculate the expected outcome.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <returns>ApiResponse of PreMatchResponse</returns>
        public Ivk.Skill.Sdk.Client.ApiResponse<PreMatchResponse> PostPreMatchWithHttpInfo(string modelId, string environment, PreMatchRequest preMatchRequest)
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->PostPreMatch");

            // verify the required parameter 'environment' is set
            if (environment == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'environment' when calling SkillApi->PostPreMatch");

            // verify the required parameter 'preMatchRequest' is set
            if (preMatchRequest == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'preMatchRequest' when calling SkillApi->PostPreMatch");

            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("environment", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.Data = preMatchRequest;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PreMatchResponse>("/api/v2/{model_id}/pre_match/{environment}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostPreMatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Useful to calculate the expected outcome.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PreMatchResponse</returns>
        public async System.Threading.Tasks.Task<PreMatchResponse> PostPreMatchAsync(string modelId, string environment, PreMatchRequest preMatchRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ivk.Skill.Sdk.Client.ApiResponse<PreMatchResponse> localVarResponse = await PostPreMatchWithHttpInfoAsync(modelId, environment, preMatchRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Useful to calculate the expected outcome.
        /// </summary>
        /// <exception cref="Ivk.Skill.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelId">ID of the skill rating model</param>
        /// <param name="environment">Environment</param>
        /// <param name="preMatchRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PreMatchResponse)</returns>
        public async System.Threading.Tasks.Task<Ivk.Skill.Sdk.Client.ApiResponse<PreMatchResponse>> PostPreMatchWithHttpInfoAsync(string modelId, string environment, PreMatchRequest preMatchRequest, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'modelId' is set
            if (modelId == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'modelId' when calling SkillApi->PostPreMatch");

            // verify the required parameter 'environment' is set
            if (environment == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'environment' when calling SkillApi->PostPreMatch");

            // verify the required parameter 'preMatchRequest' is set
            if (preMatchRequest == null)
                throw new Ivk.Skill.Sdk.Client.ApiException(400, "Missing required parameter 'preMatchRequest' when calling SkillApi->PostPreMatch");


            Ivk.Skill.Sdk.Client.RequestOptions localVarRequestOptions = new Ivk.Skill.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ivk.Skill.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("model_id", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(modelId)); // path parameter
            localVarRequestOptions.PathParameters.Add("environment", Ivk.Skill.Sdk.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.Data = preMatchRequest;

            // authentication (api_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-ivk-apikey", this.Configuration.GetApiKeyWithPrefix("x-ivk-apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PreMatchResponse>("/api/v2/{model_id}/pre_match/{environment}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostPreMatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
